sudo: false
language: c
compiler:
  - clang

os:
  - linux
  - osx

env:
  - ARCH=x86_64
  - ARCH=i686
script:
  - ./comp

branch:
  only:
    - master

addons:
  apt:
    package:
      - gcc-multilib
