#!/bin/bash

make -C libft re
clang -Wall -Wextra -I libft/includes -o get_next_line.o -c get_next_line.c 
clang -Wall -Wextra -I libft/includes -o main.o -c main.c
if [ -f get_next_line.o ]; then
	clang -o test_gnl main.o get_next_line.o -I libft/includes -L libft/ -lft
	rm main.o get_next_line.o
	printf " \e[35m[ \e[36mCompiled!\e[35m ]\e[0m\n"
else
	printf " \e[35m[ \e[31mNot compiled!\e[35m ]\e[0m\n"
fi
